basic = [   'begin',
             'call',
             'const',
             'do',
             'end',
             'if',
             'odd',
             'procedure',
             'read',
             'then',
             'var',
             'while',
             'write']
operator = ['+',
            '-',
            '*',
            '/',
            'odd',
            '=',
            '<>',
            '<',
            '<=',
            '>',
            '>=',
            ':=',
            ]
bounder = [ '(',
            ')',
            ',',
            ';',
            '.',
            ]