basic = {   'begin':'beginsym',
             'call':'callsym',
             'const':'constsym',
             'do':'dosym',
             'end':'endsym',
             'if':'ifsym',
             'odd':'oddsym',
             'procedure':'proceduresym',
             'read':'readsym',
             'then':'thensym',
             'var':'varsym',
             'while':'whilesym',
             'write':'writesym'}
operator = {'+':'plus',
            '-':'minus',
            '*':'times',
            '/':'slash',
            'odd':'oddsym',
            '=':'eql',
            '<>':'neq',
            '<':'lss',
            '<=':'leq',
            '>':'gtr',
            '>=':'geq',
            ':=':'becomes',
            }
bounder = { '(':'lparan',
            ')':'rparan',
            ',':'comma',
            ';':'semicolon',
            '.':'period',
            }